### ISSUE TITLE
Clashes with XStream by ThoughtWorks

### ISSUE THREAD

**Issue by neilellis** [benas/xstream#3]
This is a very well known and used library, I would strongly suggest considering a project rename and/or a rename of the main static class to avoid confusion.

(btw. great looking library, looks very promising)

**Comment by fmbenhassine** [comment]
Thank you! 
There is no clash since the groupId is different. But I should consider rename the project to avoid any confusion. I thought about UStream for "Unix Stream"

**Comment by fmbenhassine** [comment]
Just renamed the project to UStream for Unix Stream (pronounced "YouStream" for "YounixStream :smirk: )
Hope there is no more confusion now ..
